In [202]:
"""
    Here we test the coarse graining class.
"""

%reload_ext autoreload
%autoreload 2

import sys
sys.path.insert(1,'./../src')

import methods
import networkx as nx
import numpy as np
import random_walk as rw
import scipy


In [203]:
# test on 1D line
n = 9
G = nx.Graph()
for i in range(0,n):
    G.add_edge(i,i+1, weight=1)

In [204]:
# construct partition
nodes = list(G.nodes)
part = []
for node in nodes:
    if node < 5:
        part.append(0)
    # elif node > 8:
    #     part.append(2)
    else:
        part.append(1)


In [205]:
cG = methods.CoarseGraph(G, part)

In [206]:
cG.edges.data()

EdgeDataView([(0, 0, {'weight': 0.8333333333333335}), (0, 1, {'weight': 0.1111111111111111}), (1, 1, {'weight': 0.8333333333333335})])

In [207]:
# build random walk class and test coarse against original.
walk = rw.RandomWalk(G)

In [215]:
walk._setup_inc_trans(0, inc=np.array(part))

k = 10000000
for i in range(k):
    walk._step_inc_trans()

In [209]:
print(walk.inc_T)
print(walk.inc_T/np.sum(walk.inc_T, axis=0))

[[2226548  277562]
 [ 277562 2218328]]
[[0.88915743 0.11120763]
 [0.11084257 0.88879237]]


In [216]:
print(walk.inc_T[0,0] / walk.inc_T[0,1])
print(walk.inc_T[1,1] / walk.inc_T[0,1])

8.027705615244566
7.962951835407057


In [211]:
walk2 = rw.RandomWalk(cG)

In [212]:
walk2.T

array([[0.88235294, 0.11764706],
       [0.11764706, 0.88235294]])

In [213]:
walk2._setup_inc_trans(0, inc=[0,1])

k = 5000000
for i in range(k):
    walk2._step_inc_trans()

In [217]:
print(walk2.inc_T)
print(walk2.inc_T/np.sum(walk2.inc_T, axis=0))
print(walk2.inc_T[0,0] / walk2.inc_T[0,1])
print(walk2.inc_T[1,1] / walk2.inc_T[0,1])

[[2207568  293875]
 [ 293875 2204682]]
[[0.88251781 0.11761789]
 [0.11748219 0.88238211]]
7.511928541046363
7.502108039132284
